# Generated by Django 4.2.2 on 2023-06-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'test_scores',
            },
        ),
    ]
