# Generated by Django 4.2.2 on 2023-06-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_test', '0002_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_score',
            name='test',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
