# Generated by Django 4.2.2 on 2023-06-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_test', '0003_user_score_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_score',
            name='user',
            field=models.CharField(default='it_user', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('it_user', 'it_user'), ('staff', 'staff')], max_length=10),
        ),
    ]
