# Generated by Django 4.2.2 on 2023-06-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_test', '0004_user_score_user_alter_customuser_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_score',
            name='grade',
            field=models.CharField(default='NONe', max_length=100),
        ),
    ]
